### ISSUE TITLE
Just a question!

### ISSUE THREAD

**Issue by mitinull** [nika-va/dog_breed_identification#1]
Hello nika-va!
I sent a pull request to zero mastery organization but I didn't get the badge!
I also joined the organization but it doesn't appear on my profile!
Do you know why is that? Did you do some extra work to do it?

**Comment by nika-va** [comment]
Hi. In my case, bot automatically accepted the pull request. Be sure you did everything right. And about organization, first assure that you've actually joined there, because I was searching to enable it on my profile without joining, too 😁, and if you have yet it still doesn't show up then, please follow these instructions: 
[publicize your membership](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-your-membership-in-organizations/publicizing-or-hiding-organization-membership)

**Comment by mitinull** [comment]
Thanks a lot 👍🙏
The organization thing worked. 👍 ( I had not made it public.)
The bot have accepted my pull request but I didn't get the badge. ( The
pull shark 🦈 badge that you have.🙂)

**Comment by nika-va** [comment]
try to tag some of them like @anaeogie and explain the situation

**Comment by mitinull** [comment]
Yeah. Will do.👍
Thanks.

**Comment by nika-va** [comment]
You're welcome ! 😊
